import { Inter } from "next/font/google";
import "./globals.css";
import SideNavbar from "@/components/SideNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`min-h-screen w-full bg-white text-black flex ${inter.className}`}
            >
                {" "}
                <SideNavbar />
                <div className="p-8 w-full">{children}</div>
            </body>
        </html>
    );
}
